
spring.application.name=cati-tcc

server.servlet.context-path=/cati/api
spring.datasource.url=jdbc:h2:mem:tccdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Essa frase vai ser usada para a criptografar os tokens como uma assinatura digital que sera comparada, achei icone
api.security.token.secret=SaoDuasFloresUnidasDuasRosasNascidasTalvezDoMesmoArrebolVivendoNoMesmoGalhoDaMesmaGotaDeOrvalhoDoMesmoRaioDeSol123

# Define que o armazenamento de sessao sera via JDBC
spring.session.store-type=jdbc

# Cria as tabelas automaticamente use always para desenvolvimento
spring.session.jdbc.initialize-schema=always

# Nome da tabela caso queira mudar o padrao e SPRING_SESSION
spring.session.jdbc.table-name=SPRING_SESSION